import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Header from "./Header";
import Footer from "./Footer";


export const metadata: Metadata = {
  title: "Next.js-blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
